name: Deploy Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build the project
      run: |
        echo "Building the project..."
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      # Aprovação manual será exigida para o deploy
    steps:
    - name: Deploy to production
      run: |
        echo "Deploying to production..."

